apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: priporocanjestoritev-service-monitor
  labels:
    team: katalogteam
spec:
  selector:
    matchLabels:
      app: priporocanje-storitev
  endpoints:
  - port: server